routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are aded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('auth.login');
    return view('auth.log');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/users', 'UserController@users');
Route::post('/adduser', ['uses'=>'UserController@adduser', 'as'=>'adduser']);
Route::post('/adduserlevel', ['uses'=>'UserController@adduserlevel', 'as'=>'adduserlevel']);
Route::post('/edituser', ['uses'=>'UserController@edituser', 'as'=>'edituser']);
Route::post('/deleteuser', ['uses'=>'UserController@deleteuser', 'as'=>'deleteuser']);
Route::post('/get_subcounties', ['uses'=>'UserController@get_subcounties', 'as'=>'get_subcounties']);

Route::get('/sa_person', 'SA_PERSONS_CONTROLLER@SA_persons');
Route::post('/add_sa_person', ['uses'=>'SA_PERSONS_CONTROLLER@add_sa_person', 'as' => 'add_sa_person']);

Route::get('/corp', 'CorpController@Corp');
Route::post('/addcorp', ['uses'=>'CorpController@addcorp', 'as' => 'addcorp']);
Route::post('/editcorp', ['uses'=>'CorpController@editcorp', 'as'=>'editcorp']);
Route::post('/deletecorp', ['uses'=>'CorpController@deletecorp', 'as'=>'deletecorp']);

Route::get('/healthofficer', 'HealthOfficerController@healthofficer');
Route::post('/addhealthofficer', ['uses'=>'HealthOfficerController@addhealthofficer', 'as' => 'addhealthofficer']);
Route::post('/edithealthofficer', ['uses'=>'HealthOfficerController@edithealthofficer', 'as'=>'edithealthofficer']);
Route::post('/deletehealthofficer', ['uses'=>'HealthOfficerController@deletehealthofficer', 'as'=>'deletehealthofficer']);

Route::get('/supplier', 'SupplierController@supplier');
Route::post('/addsupplieragent', ['uses'=>'SupplierController@addsupplieragent', 'as' => 'addsupplieragent']);
Route::post('/addsupplier', ['uses'=>'SupplierController@addsupplier', 'as' => 'addsupplier']);
Route::post('/editsupplier', ['uses'=>'SupplierController@editsupplier', 'as'=>'editsupplier']);
Route::post('/deletesupplier', ['uses'=>'SupplierController@deletesupplier', 'as'=>'deletesupplier']);

Route::get('/myproducts', ['uses' => 'ProductsController@products', 'as' => 'myproducts']);
Route::get('/products', ['uses' => 'ProductsController@getproducts', 'as' => 'products']);
Route::post('/addproducts', ['uses'=>'ProductsController@addproducts', 'as'=>'addproducts']);
Route::post('/addproductssupplier', ['uses'=>'ProductsController@add_products_supplier', 'as'=>'addproductssupplier']);
Route::post('/editproducts', ['uses'=>'ProductsController@editproducts', 'as'=>'editproducts']);
Route::post('/deleteproducts', ['uses'=>'ProductsController@deleteproducts', 'as'=>'deleteproducts']);
Route::get('/getproducts', ['uses' => 'ProductsController@getproducts', 'as' => 'getproducts']);

Route::get('/informationcenter', ['uses' => 'InformationCenterController@informationcenter', 'as' => 'informationcenter']);
// Route::get('/products', ['uses' => 'InformationCenterController@getproducts', 'as' => 'products']);
Route::post('/addinfor', ['uses'=>'InformationCenterController@addinfor', 'as'=>'addinfor']);

Route::get('/broadcast', ['uses' => 'MessagingController@broadcast', 'as' => 'broadcast']);
Route::post('/addbroadcast', ['uses'=>'MessagingController@addbroadcast', 'as'=>'addbroadcast']);
Route::post('/editbroadcast', ['uses'=>'MessagingController@editbroadcast', 'as'=>'editbroadcast']);
Route::post('/deletebroadcast', ['uses'=>'MessagingController@deletebroadcast', 'as'=>'deletebroadcast']);

//stock routes
Route::get('/stocks', 'StockController@index');
Route::post('/addstock', ['uses'=>'StockController@addstock', 'as'=>'addstock']);
Route::post('/editstock', ['uses'=>'StockController@editstock', 'as'=>'editstock']);
Route::get('/stockbalance', ['uses'=>'StockController@stockbalance', 'as'=>'stockbalance']);
Route::get('/stockmovement', ['uses'=>'StockController@movement', 'as'=>'stock-movement']);

//orders routes
Route::get('/adminorders', 'Admin_ordersController@admin_orders');
Route::get('/orders', 'OrderController@index');
Route::get('/orderssuppliers', 'OrderController@orderssuppliers');
Route::post('/addorder', ['uses'=>'OrderController@addstock', 'as'=>'addorder']);
Route::post('/editorder', ['uses'=>'OrderController@editorder', 'as'=>'editorder']);
//Route::get('vieworderdetails', 'OrderController@vieworderdetails');
Route::get('/vieworderdetails/{id}', 'OrderController@vieworderdetails');
//Route::post('/vieworderdetails', 'OrderController@vieworderdetails');
Route::post('/updateorder', ['uses'=>'OrderController@updateorder', 'as'=>'updateorder']);
Route::post('/addsaorder', ['uses'=>'OrderController@addsaorder', 'as'=>'addsaorder']);
Route::post('/disapproveorder', ['uses'=>'OrderController@disapproveorder', 'as'=>'disapproveorder']);


Route::get('/report', 'ReportController@report');
Route::get('/farmers', 'FarmerController@farmers');

Route::get('/agent', ['uses' => 'AgentController@agent', 'as' => 'agent']);
Route::get('/addagent', ['uses'=>'AgentController@addagent', 'as'=>'addagent']);
Route::post('/editagent', ['uses'=>'AgentController@editagent', 'as'=>'editagent']);
Route::post('/deleteagent', ['uses'=>'AgentController@deleteagent', 'as'=>'deleteagent']);
Route::get('/corps', 'CorpController@corp');

Route::get('/process_inbox', 'InboxController@process');

// Route::get('/ordertest', 'InboxController@order');

app/Corp.php
<?php
	
	namespace App;
	
	use Illuminate\Database\Eloquent\Model;
	
	class Corp extends Model
	{
		public $table = 'corps';
		protected $primaryKey = 'corp_id';
		
		/**
		 * The attributes that are mass assignable.
		 *
		 * @var array
		 */
		protected $fillable = [
				'corp_id', 'person_id', 'is_vet', 'vet_reg_number', 'create_at', 'created_by', 'updated_at', 'updated_by',
		];
		
		protected function getCreatedAtAttribute($value)
		{
			return $value;
		}
		
		public function person()
		{
			return $this->belongsTo('App\Person', 'person_id', 'person_id');
		}
		
	}

resources/views/admin_orders.blade.php
@extends('layouts.master')
@section('styles')

@endsection('styles')
@section('content')
		<div id="main-container">
			<div id="breadcrumb">
				<ul class="breadcrumb">
					 <li><i class="fa fa-home"></i><a href="{{ url('/home') }}"> Home</a></li>
					 <li class="active">All Orders</li>
				</ul>
			</div><!-- /breadcrumb-->

			<div class="padding-md">
				<div class="row">
				   
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="panel panel-default table-responsive">
							<div class="panel-heading">
								All Order Details
							</div>
							<div class="padding-md clearfix">
							<table class="table" id="dataTable">
								<thead class="thead-dark">
									<tr>
									<th scope="col">No.</th>									
									<th scope="col">Product Name</th>
									<th scope="col">Order From</th> <!--Names of e.g Farmer, Corp, SA etc -->
									<th scope="col">Order To</th> <!--Names of e.g Farmer, Corp, SA etc -->
									<th scope="col">Order Status</th> <!--e.g Delivered, Pending etc -->
									<th scope="col">Quantity Ordered</th>
									<th scope="col">Quantity Delivered</th>
									<th scope="col">Order Date</th>
									<th scope="col">Comments</th>
									</tr>
								</thead>
								<tbody>
								@foreach($order_details as $order_detail)
									<tr>
										<td>{{ $loop->iteration }}</td>
										<td>{{$order_detail->product->product_name}}</td>
										<!-- <td>{{$order_detail->quantity_ordered}}</td> -->
										<td>{{$order_detail->order->client->first_name}} {{$order_detail->order->client->last_name}}</td>									
										<td>{{$order_detail->order->seller->first_name}} {{$order_detail->order->seller->last_name}}</td>
										if({{$order_detail->order->status}} == 0){
											<td>Pending</td>
										}elseif({{$order_detail->order->status}} == 1){
											<td>In Progress</td>
										}else{
											<td>Delivered</td>
										}
										<!-- <td>{{$order_detail->order->status}}</td> -->
										<td>{{$order_detail->quantity_ordered}}</td>
										<td>{{$order_detail->quantity_delivered}}</td>
										<td>{{$order_detail->order->created_at}}</td>
                                        <td>{{$order_detail->comments}}</td>
									</tr>
 								 @endforeach
								</tbody>
							</table>
                            </div>
                            </div>

					</div>
				</div><!-- /row-->
				<div class="row">

				</div><!-- /.row -->
			</div><!-- /.padding-md -->
		</div><!-- /main-container -->
        	
@endsection
@section('scripts')

<script src="/assets/js/datatables.js"></script>
<script src="/assets/js/order.js"></script>
<script type="text/javascript">
	$('.category').select2();
</script>

@endsection

resources/views/admin_products.blade.php
@extends('layouts.master')
@section('styles')

@endsection('styles')
@section('content')
		<div id="main-container">
			<div id="breadcrumb">
				<ul class="breadcrumb">
					 <li><i class="fa fa-home"></i><a href="{{ url('/home') }}"> Home</a></li>
					 <li class="active">Products</li>	 
				</ul>
			</div><!-- /breadcrumb-->

            <div class="padding-md">
				<div class="row">
					<div class="col-sm-6 col-md-12">
						<div class="col-md-12" style="padding-bottom:10px">
							<button type="button" id="modalbtn" class="btn btn-info btn-sm pull-left" data-toggle="modal" data-target="#addProductModal"> <i class="fa fa-plus" aria-hidden="true"></i> Add Product</button>
						</div>

					</div><!-- /.col -->					
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="panel panel-default table-responsive">
							<div class="panel-heading">
								Users
								<span class="label label-info pull-right" id="totalspan">{{count($products)}} Products </span>
							</div>
							<div class="padding-md clearfix">
							<table class="table" id="products_dataTable">
								<thead class="thead-dark">
									<tr>
                                        <th scope="col">No </th>
                                        <th scope="col">Product Name</th>
                                        <th scope="col">Product Code</th>
                                        <th scope="col">Date Added </th>
                                        <th scope="col">Action</th>
									</tr>
								</thead>
								<tbody>
								@foreach($products as $product)
									<tr>
										<td>{{ $loop->iteration }}</td>
										<td>{{$product->product_name}}</td>
										<td>{{$product->product_code}}</td>
										<td>{{$product->created_at}}</td>
										<!-- <td><a onclick="editProducts({{$product->product_id}}, '{{$product->product_name}}', '{{$product->product_code}}');" class="btn btn-info btn-xs" style="margin-right:3px;"><i class="fa fa-pencil" aria-hidden="true"></i></a> -->
                                        <td><a data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" style="margin-right:3px;" href="#lightCustomModal"  class="btn btn-xs btn-danger lightCustomModal_open btndeleteproduct" data-user="{{ $product->product_id }}"> <i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
									</tr>
 								 @endforeach
								</tbody>
							</table>
                            </div>
                            </div>

					</div>
				</div><!-- /row-->
				<div class="row">
					
				</div><!-- /.row -->												
			</div><!-- /.padding-md -->			
		</div><!-- /main-container -->
		@if(Auth::user()->user_level == 1)
        <div class="modal fade" id="addProductModal" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="exampleModalLongTitle">Add Product</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							<form role="form" county="post" action="<?php echo URL::route('addproducts') ?>" id="addproductform">
								{{ csrf_field() }}
								<div class="form-group">
									<label>Product Name</label>
									<input type="text" class="form-control input-sm" name="product_name" placeholder="Product Name">
								</div><!-- /form-group -->
								<div class="form-group">
									<label>Product Code</label>
										<input type="text" class="form-control input-sm" name="product_code" placeholder="Product Code">
								</div><!-- /form-group -->
												
								<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
								<button type="submit" id="addproductbtn" class="btn btn-success btn-sm pull-right"> <i class="fa fa-plus" aria-hidden="true"></i> Add Product</button>
							</form>
						</div>
					</div>
				</div>
            </div>
			@else
			<div class="modal fade" id="addProductModal" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="exampleModalLongTitle">Add Product</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							<form role="form" county="post" action="<?php echo URL::route('addproductssupplier') ?>" id="addproductssupplierform">
								{{ csrf_field() }}
								<div class="form-group">

								    
											
										<label>Product</label>
										<select  multiple class="form-control input-sm category" data-width="100%" id="product_id" name="product_id[]">
										
										<!-- <option value="">Select Product</option> -->
									
											@if (count($products) > 0)
												@foreach($products as $product)
												<option value="{{$product->product_id }}">{{ ucwords($product->product_name) }}</option>
													@endforeach
											@endif
										</select>
										
									
								</div><!-- /form-group -->
											
								<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
								<button type="submit" id="addproductbtnsupplier" class="btn btn-success btn-sm pull-right"> <i class="fa fa-plus" aria-hidden="true"></i> Add Product</button>
							</form>
						</div>
					</div>
				</div>
            </div>
			@endif
@endsection
@section('scripts')
<script>
$(".category").select2();
</script>
<script src="/assets/js/datatables.js"></script>
<script src="/assets/js/products.js"></script>

@endsection

resources/views/broadcast.blade.php
@extends('layouts.master')
@section('styles')

@endsection('styles')
@section('content')
		<div id="main-container">
			<div id="breadcrumb">
				<ul class="breadcrumb">
					 <li><i class="fa fa-home"></i><a href="{{ url('/home') }}"> Home</a></li>
					 <li class="active">Broadcast</li>	 
				</ul>
			</div><!-- /breadcrumb-->

            <div class="padding-md">
				<div class="row">
					<div class="col-sm-6 col-md-12">
						<div class="col-md-12" style="padding-bottom:10px">
							<button type="button" id="modalbtn" class="btn btn-info btn-sm pull-left" data-toggle="modal" data-target="#addBroadcastModal"> <i class="fa fa-plus" aria-hidden="true"></i> Add Broadcast Message</button>
						</div>

					</div><!-- /.col -->					
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="panel panel-default table-responsive">
							<div class="panel-heading">
								Broadcast Messages
								<span class="label label-info pull-right" id="totalspan">{{count($broadcast)}} Broadcast </span>
							</div>
							<div class="padding-md clearfix">
							<table class="table" id="broadcast_dataTable">
								<thead class="thead-dark">
									<tr>
                                        <th scope="col">No </th>
                                        <th scope="col">Broadcast Name</th>
                                        <th scope="col">Broadcast Content</th>
                                        <th scope="col">Date Created </th>
                                        <th scope="col">Created By</th>
                                        <th scope="col">Action</th>
									</tr>
								</thead>
								<tbody>
								@foreach($broadcast as $bcast)
									<tr>
										<td>{{ $loop->iteration }}</td>
										<td>{{$bcast->broadcast_name}}</td>
										<td>{{$bcast->broadcast_content}}</td>
										<td>{{$bcast->created_at}}</td>
										<!-- <td>{{$bcast->creator->first_name}}</td> -->
										<td>{{ucwords($bcast->creator->first_name)}} {{ucwords($bcast->creator->last_name)}}</td>
										<td><a onclick="editbroadcast({{$bcast->broadcast_id}}, '{{$bcast->broadcast_name}}', '{{$bcast->broadcast_content}}');" class="btn btn-info btn-xs" style="margin-right:3px;"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                        <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" style="margin-right:3px;" href="#lightCustomModal"  class="btn btn-xs btn-danger lightCustomModal_open btndeletebroadcast" data-user="{{ $bcast->broadcast_id }}"> <i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
									</tr>
 								 @endforeach
								</tbody>
							</table>
                            </div>
                            </div>

					</div>
				</div><!-- /row-->
				<div class="row">
					
				</div><!-- /.row -->												
			</div><!-- /.padding-md -->			
		</div><!-- /main-container -->

        <div class="modal fade" id="addBroadcastModal" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="exampleModalLongTitle">Add Broadcast</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							<form role="form" county="post" action="<?php echo URL::route('addbroadcast') ?>" id="addbroadcastform">
								{{ csrf_field() }}
								<div class="form-group">
									<label>Broadcast Name</label>
									<input type="text" class="form-control input-sm" name="broadcast_name" placeholder="Broadcast Name">
								</div><!-- /form-group -->
								<div class="form-group">
									<label>Broadcast Content</label>
										<input type="text" class="form-control input-sm" name="broadcast_content" placeholder="Broadcast Content">
								</div><!-- /form-group -->
												
								<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
								<button type="submit" id="addbroadcastbtn" class="btn btn-success btn-sm pull-right"> <i class="fa fa-plus" aria-hidden="true"></i> Add Broadcast</button>
							</form>
						</div>
					</div>
				</div>
            </div>
@endsection
@section('scripts')

<script src="/assets/js/datatables.js"></script>
<script src="/assets/js/broadcast.js"></script>

@endsection

resources/views/farmers.blade.php
@extends('layouts.master')
@section('styles')

@endsection('styles')
@section('content')
		<div id="main-container">
			<div id="breadcrumb">
				<ul class="breadcrumb">
					 <li><i class="fa fa-home"></i><a href="{{ url('/home') }}"> Home</a></li>
					 <li class="active">Farmers</li>
				</ul>
			</div><!-- /breadcrumb-->

			<div class="padding-md">
				<div class="row">
					<div class="col-sm-6 col-md-12">
						<div class="col-md-12" style="padding-bottom:10px">
							<!-- <button type="button" id="modalbtn" class="btn btn-info btn-sm pull-left" data-toggle="modal" data-target="#addUserModal"> <i class="fa fa-plus" aria-hidden="true"></i> Add User</button> -->
						</div>

					</div><!-- /.col -->
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="panel panel-default table-responsive">
							<div class="panel-heading">
							Farmers
								<span class="label label-info pull-right" id="totalspan">{{count($farmers)}} Farmers </span>
							</div>
							<div class="padding-md clearfix">
							<table class="table" id="dataTable">
								<thead class="thead-dark">
									<tr>
									<th scope="col">No.</th>
									<th scope="col">Name</th>
									<th scope="col">ID No.</th>
									<th scope="col">Phone No.</th>
									<th scope="col">County</th>
									<th scope="col">Sub County</th>
									<th scope="col">Corp</th>
									<th scope="col">Location</th>
									<th scope="col">Date Created</th>
									<!-- <th scope="col">Created By</th> -->
									<th scope="col">Action</th>
									</tr>
								</thead>
								<tbody>
								@foreach($farmers as $farmer)
									<tr>
										<td>{{ $loop->iteration }}</td>
										<td>{{ucwords($farmer->person->first_name)}} {{ucwords($farmer->person->last_name)}}</td>
										<td>{{$farmer->person->id_number}}</td>
										<td>{{$farmer->person->phone_no}}</td>
										<td>{{$farmer->person->sub_county->county->name}}</td>
										<td>{{$farmer->person->sub_county->name}}</td>
										<td>{{$farmer->person->first_name}}</td>
										<td>{{$farmer->location}}</td>
                                        <td>{{$farmer->created_at}}</td>
                                        <td><a onclick="editfarmer({{$farmer->farmer_id}}, '{{ucwords($farmer->person->first_name)}}','{{ucwords($farmer->person->last_name)}}', {{$farmer->person->id_number}}, '0{!! substr($farmer->person->phone_no, 4) !!}', {{$farmer->person->sub_county->county->id}}, {{$farmer->person->sub_county->id}});" class="btn btn-info btn-xs" style="margin-right:3px;"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                        <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" style="margin-right:3px;" href="#lightCustomModal"  class="btn btn-xs btn-danger lightCustomModal_open btndeletecorp" data-user="{{ $farmer->farmer_id }}"> <i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
									</tr>
 								 @endforeach
								</tbody>
							</table>
                            </div>
                            </div>

					</div>
				</div><!-- /row-->
				<div class="row">

				</div><!-- /.row -->
			</div><!-- /.padding-md -->
		</div><!-- /main-container -->


        <!-- Add user modal -->
		<div class="modal fade" id="addUserModal" tabindex="-1" role="dialog" aria-hidden="true">
					<div class="modal-dialog" role="document">
						<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="exampleModalLongTitle">Add User</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							<form role="form" county="post" action="<?php echo URL::route('adduser') ?>" id="adduserform">
												{{ csrf_field() }}
												<div class="form-group">
													<label>First Name</label>
													<input type="text" class="form-control input-sm" name="first_name" placeholder="First Name">
												</div><!-- /form-group -->
												<div class="form-group">
													<label>First Name</label>
													<input type="text" class="form-control input-sm" name="last_name" placeholder="Last Name">
												</div><!-- /form-group -->

												<div class="form-group">
													<label>ID Number</label>
												<input type="text" class="form-control input-sm"  name="id_num" id="id_num">
												</div>
												<div class="form-group">
													<label>Phone Number</label>
													<input type="text" class="form-control input-sm" name="phone_no" placeholder="0700000000">
												</div><!-- /form-group -->
												<div class="form-group">
													<label>Email</label>
													<input type="email" class="form-control input-sm" name="email" placeholder="example@example.org">
												</div><!-- /form-group -->
												<div class="form-group" >
													<!-- <label>County</label>
													<select class="form-control input-sm category" data-width="100%" id="county" name="county_id">
												<option value="">Select County</option>
													@if (count($counties) > 0)
														@foreach($counties as $county)
														<option value="{{$county->id }}">{{ ucwords($county->name) }}</option>
															@endforeach
													@endif
												</select> -->
												</div><!-- /form-group -->
												<div class="form-group">
													<label>Sub County</label>
													<select class="form-control input-sm category" data-width="100%" id="sub_county" name="sub_county_id" >
												<option value="">Select Sub County</option>

												</select>
												</div><!-- /form-group -->
												<div class="form-group">
													<label>User Level</label>
													<select class="form-control input-sm category" data-width="100%" id="level" name="user_level_id" >
												<option value="">Select User Level</option>
												@if (count($userlevels) > 0)
														@foreach($userlevels as $userlevel)
														<option value="{{$userlevel->user_level_id }}">{{ ucwords($userlevel->user_level_name) }}</option>
															@endforeach
													@endif
												</select>
												</div><!-- /form-group -->

												<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
												<button type="submit" id="adduserbtn" class="btn btn-success btn-sm pull-right"> <i class="fa fa-plus" aria-hidden="true"></i> Add User</button>
											</form>
						</div>
						</div>
					</div>
        </div>

        <!-- Edit user modal -->


        <div class="modal fade" id="editUserModal" tabindex="-1" role="dialog" aria-hidden="true">
					<div class="modal-dialog" role="document">
						<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="exampleModalLongTitle">Edit User</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							
						</div>
						</div>
					</div>
        </div>


        	<!-- pop confirm modal -->
	<div class="custom-popup light width-100" id="lightCustomModal">
		<div class="padding-md">
			<h4 class="m-top-none"> Do you want to continue? </h4>
		</div>

		<div class="text-center">
			<a href="#" class="btn btn-success m-right-sm lightCustomModal_close btndeleteuser-confirm">Confirm</a>
			<a href="#" class="btn btn-danger lightCustomModal_close">Cancel</a>
		</div>
	</div>
	<!-- pop confirm modal -->
@endsection
@section('scripts')

<script src="/assets/js/datatables.js"></script>
<script src="/assets/js/user.js"></script>
<script type="text/javascript">
	$('.category').select2();
</script>

@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection